# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'meshview_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1164, 803)
        MainWindow.setAcceptDrops(True)
        
    def dragEnterEvent(self, e):
        """
        This function will detect the drag enter event from the mouse on the main window
        """
        print('drag-enter')
        if e.mimeData().hasUrls:
            e.accept()
        else:
            e.ignore()

    def dragMoveEvent(self,e):
        """
        This function will detect the drag move event on the main window
        """
        print('drag-move')
        if e.mimeData().hasUrls:
            e.accept()
        else:
            e.ignore()
    
    def dropEvent(self, e): 
        """
		This function will enable the drop file directly on to the 
		main window. The file location will be stored in the self.filename
		"""
        print('drag-drop')
        if e.mineData().hasurls(): 
            e.setDropAction(QtCore.Qt.CopyAction)
            e.accetp()
            for url in e.mimeData().urls(): 
                fname = str(url.toLocalFile())
        else: 
            e.ignore()

        print(fname)
            
        self.call2Dmesh(manualfile=fname)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
